"""Configure all training and experiment settings."""

from pathlib import Path

AGENT_DIR = Path(__file__).parent
EXPERIMENTS_DIR = AGENT_DIR / "experiments"

ACTIONS = ("UP", "RIGHT", "DOWN", "LEFT", "WAIT")

EXPERIMENT_NAME = "<EXP_NAME>"
DESCRIPTION = "<DES>"

RESUME_TRAINING = False
RESTART_EXPERIMENT = True

OBSERVATION_COUNT = 9

LEARNING_RATE = 3e-4
GAMMA = 0.99
GAE_LAMBDA = 0.95
CLIP_EPSILON = 0.1
VALUE_COEF = 0.5
ENTROPY_COEF = 0.005
UPDATE_EPOCHS = 3
MINIBATCH_SIZE = 64
